### ISSUE TITLE
QMake buildsystem needs love

### ISSUE THREAD

**Issue by winterz** [cornelius/libkode#2]
For KDSoap we still need to support the qmake buildsystem.

I see some problems already:
 * common/common.pro, libkode/libkode.pro, schema/schema.pro refer to kdwsdl2cpp INCUDEPATHs
 * common/common.pro, libkode/libkode.pro, schema/schema.pro include $${TOP_SOURCE_DIR}/variables.pri which is only found in kdsoap as the TOP_SOURCE_DIR
* common/common.pro, libkode/libkode.pro, schema/schema.pro need to add $${TOP_SOURCE_DIR}/kdwsdl2cpp/libkode to their INCLUDEPATHs

Not only that, there should be a top-level libkode.pro for building and installing as a stand-alone project

**Comment by martonmiklos** [comment]
@winterz  @dfaure-kdab I have started to integrate the libkode back to the kode, and this seems to be the first issue what I need to address.

My plan is:
* Convert the common, schema, libkode.pro files to pri files which does nothing else the adding headers and sources. (If you think that it makes sense to build separate libraries from the subdirs we can keep the pro files.)
* I think would make sense to rename the libkode subdirectory (and the libkode.pri file in it) to code_generation or something like that. 
* Add a project level libkode.pro and move the relevant part of the variables.pri file there.
* Add a project level libkode.pri which includes the subdir pri files. 

Any recommendation, concern about the plans above is warmly welcome!

**Comment by dfaure-kdab** [comment]
Sounds good. We don't need separate static libraries for each subdir, indeed.
