### ISSUE TITLE
Port away from QXmlInputSource

### ISSUE THREAD

**Issue by martonmiklos** [cornelius/libkode#22]
QXmlInputSource is marked deprecated in Qt 5.15, the parser codes needs to be ported to QXmlStreamReader.

**Comment by anoymouserver** [comment]
Same problem with the used QXmlSimpleReader. Both will be moved to the `core5compat` module with Qt 6.0.

**Comment by dfaure-kdab** [comment]
Done in commit f5d03ebda5f0545a42918
