### ISSUE TITLE
Add support for C++11 style member initializers

### ISSUE THREAD

**Issue by martonmiklos** [cornelius/libkode#37]
libkode supports setting initializers for (class) member variables.

However these initializers are always generated to the class constructors initializer section. 
C++11 allows the non const variables to be initialized in the member declaration, and it would be useful to support it in the libkode. (I am generating some code where some nested classes exists only as a declaration.)

@dfaure-kdab I would love to hear your opinions about this!

If the C++11 will be a requirement for KDSoap in the near future I would vote for moving the initializers to the declarations and generate only C++11 compliant code. 

If not it might be useful to add a member to the Printer which could be used to set the C++ standard of the generated code. 
At the moment no other C++11 feature came into my mind which would be useful, but later we can implement other C++11 only features this way. However it adds some maintenance burden what we should really avoid.

**Comment by dfaure-kdab** [comment]
KDSoap already requires C++11.
